### ISSUE TITLE
vehicle's forward and backward[Help]

### ISSUE THREAD

**Issue by 476793556** [ArchGryphon9362/teslabtapi#12]
Hello, have you ever tried controlling the vehicle's forward and backward movement using fsd? I checked the documentation, but it seems I couldn't find any relevant commands for that!

**Comment by ArchGryphon9362** [comment]
I haven’t tried that, but there are some RKE actions that appear to emulate keyfobs. Why don’t you try that? I think you have to send a double click command and then a hold front or press front command. This might not work though. If it doesn’t, you can try add your key with the type “keyfob”. This is all just speculation though. Good luck figuring it out :D
