### ISSUE TITLE
[Mistake] Website only shows a blank page

### ISSUE THREAD

**Issue by Urkman** [ArchGryphon9362/teslabtapi#9]
## Where is the mistake?
https://teslabtapi.lexnastin.com only shows a blank page

**Comment by ArchGryphon9362** [comment]
Weird, can you send me a screenshot please?

**Comment by Urkman** [comment]
Here:
![Bildschirm­foto 2022-11-28 um 17 44 54](https://user-images.githubusercontent.com/94297/204334022-18167ceb-7d97-485f-80ae-d2265e3ecb58.png)

**Comment by Urkman** [comment]
And one more:

![Bildschirm­foto 2022-11-28 um 17 46 39](https://user-images.githubusercontent.com/94297/204334541-5c0ba9c2-ff55-444f-a84a-90a26a0ce674.png)

**Comment by ArchGryphon9362** [comment]
Are there any errors in the console? Also if you want you can go to the docs folder in this repo, and open the individual files.

**Comment by Urkman** [comment]
OK, works in Chrome, but in Safari on MacOS...

**Comment by ArchGryphon9362** [comment]
I changed some stuff up, could you check it on Safari MacOS and where else it didn't work before please?

**Comment by ArchGryphon9362** [comment]
Great! When @Urkman responds, I'll close the issue (or he can close it himself)

**Comment by ArchGryphon9362** [comment]
Great! Closing this issue then :)
